language: R
cache: packages
sudo: required
pandoc_version: 1.19.2.1

git:
  depth: 5

branches:
  only: master

r_binary_packages:
- devtools
- bookdown
- ape
- geoscale
- knitr
- phangorn
- R.cache
- stringi
- TreeSearch
- zoo

r_github_packages:
 - TGuillerme/Inapp

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
