language: R
cache: packages
sudo: required
pandoc_version: 1.19.2.1

git:
  depth: 5

branches:
  only: master

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
  - sudo apt-get -y --reinstall install ghostscript

script:
  - ./_build.sh
  - ./_deploy.sh
